### ISSUE TITLE
Cannot open package to set/get items

### ISSUE THREAD

**Issue by Gerflargle** [MattCzyr/EnderMail#7] opened 2020-04-20 17:10 UTC
**Details**:
Forge: 1.15.2-31.1.46
EnderMail: 1.15.2-1.0.2.jar
On a dedicated server

**Symptom:**
I cannot interact with the package to place items in it. 
I can set the package down, put a stamp on it and send it off for delivery, however, when I right click it to put items in, nothing seems to happen.

**Comment by MattCzyr** [comment] 2020-04-20 23:40
A package must be un-stamped for its inventory to be accessed. To un-stamp a package, right-click the package with an empty hand while crouching.

**Comment by Schinchipanda** [comment] 2020-04-22 12:48
Hi.
I have the same problem on my server, with the same version of Forge and EnderMail.
The problem is I cannot put items in the package, I can just set it down, put a stamp on it and call the Ender mailman for delivery. I can also un-stamp the package, but that's all.
In singleplayer the mod works properly. ^^

**Comment by Gerflargle** [comment] 2020-04-22 14:52
Sorry for the late response. I finally had a chance to get more details. 

I setup a server with only endermail to prevent other conflicts, and tried again. 
Again, from the user side no errors, however, on the server log the following error message comes up when I shift right click on the un-stampeded package. 

`[minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.15.2-31.1.25.jar:31.1] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103) ~[modlauncher-5.0.0-milestone.4.jar:5.0.0-milestone.4+67+b1a340b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
        at com.chaosthedude.endermail.gui.container.PackageContainer.<init>(PackageContainer.java:33) ~[?:1.15.2-1.0.2] {re:classloading}
        at com.chaosthedude.endermail.blocks.te.PackageTileEntity.createMenu(PackageTileEntity.java:175) ~[?:1.15.2-1.0.2] {re:classloading}
        at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at com.chaosthedude.endermail.blocks.PackageBlock.func_225533_a_(PackageBlock.java:111) ~[?:1.15.2-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:269) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:334) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}`

**Comment by MattCzyr** [comment] 2020-04-28 01:06
Fixed in version 1.0.3

**Closed by MattCzyr** 2020-04-28 01:06 UTC
Labels: bug
