### ISSUE TITLE
Text fields on stamp for coordinates/locker ID are missing (Minecraft 1.16.2 + Forge 33.0.20)

### ISSUE THREAD

**Issue by Jolo248** [MattCzyr/EnderMail#20] opened 2020-08-26 00:50 UTC
Text fields on stamp for coordinates/locker ID are missing (Minecraft 1.16.2 + Forge 33.0.20 + EnderMail-1.16.2-1.1.3.jar)

See attached screenshot
![stamp](https://user-images.githubusercontent.com/69915310/91241968-29827880-e714-11ea-80ca-e45eb7f521b5.png)

**Comment by Jolo248** [comment] 2020-08-26 01:45
Did some more testings and this issue is caused by JEI (jei-1.16.2-7.1.3.19.jar)!

**Comment by Fritz9999** [comment] 2020-09-03 03:42
I am getting this same issue

**Comment by MattCzyr** [comment] 2020-09-04 20:52
Are you able to see the text fields with the default texture pack? I'm currently unable to reproduce this myself.

**Comment by Jolo248** [comment] 2020-09-04 21:17
Hello!

I just tried disabling my texture packs, and also disabling my shaders and I am still getting the issue.

Thanks!

**Comment by Jolo248** [comment] 2020-09-04 21:36
I just did some testing by removing all my mods too and now when I right-click the box with a stamp my game crashes with the following error:

`The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: com.chaosthedude.endermail.gui.StampTextField.getHeight()I
Exit Code: -1`

**Comment by Fritz9999** [comment] 2020-09-04 22:55
I am getting the same issues when it comes to the stamp GUI not displaying any input boxes using endermail with mods. I am also getting the same issue when it comes to removing all mods and the game crashes when I right-click the stamp on the box.

**Comment by MattCzyr** [comment] 2020-09-04 23:17
Fixed the issue, but I'm having some trouble building the mod with the the new Forge version. The update will be released once I figure out the build issue.

**Comment by Jolo248** [comment] 2020-09-04 23:30
> Fixed the issue, but I'm having some trouble building the mod with the the new Forge version. The update will be released once I figure out the build issue.

Cool! Thanks a lot!! :D

**Comment by Fritz9999** [comment] 2020-09-04 23:31
> Fixed the issue, but I'm having some trouble building the mod with the the new Forge version. The update will be released once I figure out the build issue.

Perfect! Thank you! I can't wait!

**Comment by MattCzyr** [comment] 2020-09-05 06:22
Fixed in version 1.1.4

**Closed by MattCzyr** 2020-09-05 06:22 UTC
Labels: bug
