### ISSUE TITLE
Game crashes when right clicking package with stamp 1.16.2

### ISSUE THREAD

**Issue by Fritz9999** [MattCzyr/EnderMail#21] opened 2020-09-03 04:17 UTC
Every time I right-click a package with the stamp, the game crashes. I am running no mods along side this mod.

**Comment by MattCzyr** [comment] 2020-09-03 17:10
Please post the crash report.

**Comment by Fritz9999** [comment] 2020-09-04 22:49
[crash-2020-09-04_17.44.22-client.txt](https://github.com/MattCzyr/EnderMail/files/5177229/crash-2020-09-04_17.44.22-client.txt)

Here's my crash report. I'm using Minecraft 1.16.2 with forge 1.16.2 33.0.32. There are no other mods I am using with this mod.

**Comment by Fritz9999** [comment] 2020-09-04 23:08
I just upgraded my forge to 33.0.37 and I am getting the same issue

**Comment by MattCzyr** [comment] 2020-09-04 23:18
Duplicate of #20, please reference that conversation instead.

**Closed by MattCzyr** 2020-09-04 23:18 UTC
Labels: bug
